# config.yaml

data:
  person_1:
    time_col: []
    agg_columns:
      - name: childnum_185L
        base_feature_name: childnum_185L_mean
        aggregation: 
          _target_: data_pipeline.pipes.mean
          _partial_: true
      - name: housetype_905L
        base_feature_name: housetype_905L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: familystate_447L
        base_feature_name: familystate_447L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: education_927M
        base_feature_name: education_927M_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true

  static_0:
    time_col: []
    agg_columns:
      - name: cardtype_51L
        base_feature_name: cardtype_51L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: credtype_322L
        base_feature_name: credtype_322L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true



  credit_bureau_a_1:
    time_col:
      - dateofrealrepmt_138D
    agg_columns:
      - name: numberofcontrsvalue_358L
        base_feature_name: numberofcontrsvalue_358L_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true
      - name: nominalrate_281L
        base_feature_name: nominalrate_281L_min
        aggregation: 
          _target_: data_pipeline.pipes.min
          _partial_: true
      - name: classificationofcontr_400M
        base_feature_name: classificationofcontr_400M_mode
        aggregation: 
          _target_: data_pipeline.pipes.mode
          _partial_: true
      - name: totaldebtoverduevalue_178A
        base_feature_name: totaldebtoverduevalue_178A_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true
      - name: overdueamount_31A
        base_feature_name: overdueamount_31A_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true
      - name: residualamount_488A
        base_feature_name: residualamount_488A_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true

  credit_bureau_a_2:
    time_col: []
    agg_columns:
      - name: collater_valueofguarantee_876L
        base_feature_name: collater_valueofguarantee_876L_mean
        aggregation: 
          _target_: data_pipeline.pipes.mean
          _partial_: true
      - name: pmts_overdue_1140A
        base_feature_name: pmts_overdue_1140A_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true
      - name: pmts_overdue_1140A
        base_feature_name: pmts_overdue_1140A_min
        aggregation: 
          _target_: data_pipeline.pipes.min
          _partial_: true
      - name: pmts_overdue_1140A
        base_feature_name: pmts_overdue_1140A_mean
        aggregation: 
          _target_: data_pipeline.pipes.mean
          _partial_: true

  applprev_2:
    time_col: []
    agg_columns:
      - name: credacc_cards_status_52L
        base_feature_name: credacc_cards_status_52L_mode
        aggregation: 
          _target_: data_pipeline.pipes.mode
          _partial_: true
      - name: credacc_cards_status_52L
        base_feature_name: credacc_cards_status_52L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true

  debitcard_1:
    time_col:
      - openingdate_857D
    agg_columns:
      - name: last180dayaveragebalance_704A
        base_feature_name: last180dayaveragebalance_704A_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: last180dayaveragebalance_704A
        base_feature_name: last180dayaveragebalance_704A_mean
        aggregation: 
          _target_: data_pipeline.pipes.mean
          _partial_: true
      - name: last180dayaveragebalance_704A
        base_feature_name: last180dayaveragebalance_704A_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true



data_pipeline:
 _target_: data_pipeline.datapipeline.PandasDataPipeline
 steps: []


model:
  model_steps: 
    -
      _target_: model.feature_selector.FeatureSelector
      features:
        - childnum_185L_mean
        - housetype_905L_last
        - familystate_447L_last
        - education_927M_last
        - cardtype_51L_last
        - credtype_322L_last
        - numberofcontrsvalue_358L_max
        - nominalrate_281L_min
        - totaldebtoverduevalue_178A_max
        - overdueamount_31A_max
        - residualamount_488A_max
        - collater_valueofguarantee_876L_mean
        - pmts_overdue_1140A_max
        - pmts_overdue_1140A_min
        - pmts_overdue_1140A_mean
        - credacc_cards_status_52L_mode
        - credacc_cards_status_52L_last
        - last180dayaveragebalance_704A_last
        - last180dayaveragebalance_704A_mean
        - last180dayaveragebalance_704A_max
        - classificationofcontr_400M_mode
    -
      _target_: model.modelorchastrator.OptBinningTransformer
      column: ["housetype_905L_last", "education_927M_last", "credacc_cards_status_52L_mode", "familystate_447L_last", "credacc_cards_status_52L_last", "classificationofcontr_400M_mode", "credtype_322L_last", "cardtype_51L_last"]
      max_n_prebins: 100
      min_prebin_size: 0.01

    -
      _target_: sklearn.ensemble.HistGradientBoostingClassifier
      learning_rate: 0.01
      categorical_features:  ["housetype_905L_last", "education_927M_last", "credacc_cards_status_52L_mode", "familystate_447L_last", "credacc_cards_status_52L_last", "classificationofcontr_400M_mode", "credtype_322L_last", "cardtype_51L_last"]
      verbose: 0
      class_weight: balanced
      max_iter: 1000
      l2_regularization: 0.3
      early_stopping: True
      max_leaf_nodes: 100
    
