site_name: Home Credit - Credit Risk Model Stability
nav:
  - Home: index.md
  - Raw Data: 
    - applprev:
      - 1_0: train_applprev_1_0.md
      - 1_1: train_applprev_1_1.md
      - 2_0: train_applprev_2.md
    - base: train_base.md
    - credit_bureau:
      - a_1_0 : train_credit_bureau_a_1_0.md
      - a_1_1 : train_credit_bureau_a_1_1.md
      - a_1_2 : train_credit_bureau_a_1_2.md
      - a_1_3 : train_credit_bureau_a_1_3.md
      - a_2_0 : train_credit_bureau_a_2_0.md
      - a_2_1 : train_credit_bureau_a_2_1.md
      - a_2_2 : train_credit_bureau_a_2_2.md
      - a_2_3 : train_credit_bureau_a_2_3.md
      - a_2_4 : train_credit_bureau_a_2_4.md
      - a_2_5 : train_credit_bureau_a_2_5.md
      - a_2_6 : train_credit_bureau_a_2_6.md
      - a_2_7 : train_credit_bureau_a_2_7.md
      - a_2_8 : train_credit_bureau_a_2_8.md
      - a_2_9 : train_credit_bureau_a_2_9.md
      - a_2_10 : train_credit_bureau_a_2_10.md
      - b_1 : train_credit_bureau_b_1.md
      - b_2 : train_credit_bureau_b_2.md
    - debitcard: train_debitcard_1.md
    - deposit: train_deposit_1.md
    - other: train_other_1.md
    - person:
      - 1 : train_person_1.md
      - 2 : train_person_2.md
    - static:
      - 0 : train_static_0_0.md
      - 1 : train_static_0_1.md
      - 2 : train_static_cb_0.md
    - tax_registry:
      - 1: train_tax_registry_a_1.md
      - 2: train_tax_registry_b_1.md
      - 3: train_tax_registry_c_1.md
theme:
  name: material
  features:
        - content.tabs.link
        - content.code.copy
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand

  palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode

        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode


plugins: 
  - search
  - table-reader
  - git-authors:
            exclude:
                - index.md

markdown_extensions:
    - tables
    - meta
    - admonition
    - pymdownx.keys
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true 



# hooks:
#   - docs\hooks\create_profile.py