[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"



[project]
name = "example_package_YOUR_USERNAME_HERE"
version = "0.0.1"
authors = [
  { name="Example Author", email="author@example.com" },
]
