# config.yaml
defaults:
  - features: features
  - _self_


data_pipeline:
 _target_: data_pipeline.datapipeline.PandasDataPipeline
 steps:
  - _target_: data_pipeline.pipelinesteps.change_missing
    _partial_: true
    columns: ['housetype_905L_last', 'education_927M_last', 'credacc_cards_status_52L_mode', 'familystate_447L_last', 'credacc_cards_status_52L_last', 'classificationofcontr_400M_mode', 'credtype_322L_last', 'cardtype_51L_last', 'cardtype_51L_mode']

model:
  model_steps: 
    - FeatureFilter:
        _target_: model.feature_selector.FeatureFilter
        features: ${features.all_features}
    - OptBinningTransformer:
        _target_: model.modelorchastrator.OptBinningTransformer
        variable_names: ${features.cat_features}
        max_n_prebins: 674
        min_prebin_size: 0.04386525609119459
        random_state: 42
    - SelectFromModel:
        _target_: model.feature_selector.FeatureSelector
        estimator: 
          _target_: model.booster.HistBooster
        threshold: 0.01

    - HistGradientBoostingClassifier:
        _target_: sklearn.ensemble.HistGradientBoostingClassifier
        learning_rate: 0.05723818391467435

        verbose: 0
        class_weight: balanced
        max_iter: 3997
        l2_regularization: 2.525756277489002
        early_stopping: True
        max_leaf_nodes: 106
        max_bins: 196
        max_depth: 605
        random_state: 42
      
hyperparameters:
  FeatureFilter:
    features:
      default: ${features.all_features}
  OptBinningTransformer:
    max_n_prebins:
      type: int
      max: 1000
      min: 2
      default: 100
    min_prebin_size:
      type: float
      max: 0.5
      min: 0.02
      default: 0.05
    variable_names:
      default: ${features.cat_features}
    random_state:
      default: 42
  HistGradientBoostingClassifier:
    learning_rate:
      type: float
      max: 1
      min: 0.01
      default: 0.1
    max_iter:
      type: int
      max: 10000
      min: 100
      default: 1000
    l2_regularization:
      type: float
      max: 10
      min: 0.001
      default: 0.3
    early_stopping:
      default: True
    max_leaf_nodes:
      type: int
      max: 1000
      min: 10
      default: 100
    max_depth:
      type: int
      max: 1000
      min: 1
      default: 100
    max_bins:
      type: int
      max: 255
      min: 2
      default: 255
    class_weight:
      default: balanced
    random_state:
      default: 42
