# config.yaml
defaults:
  - features: features
  - _self_



data_pipeline:
 _target_: data_pipeline.datapipeline.PandasDataPipeline
 steps: []

model:
  model_steps: 
    - FeatureSelector:
        _target_: model.feature_selector.FeatureSelector
        features: ${features.all_features}
    - OptBinningTransformer:
        _target_: model.modelorchastrator.OptBinningTransformer
        column: ${features.cat_features}

    - HistBooster:
        _target_: model.modelorchastrator.HistBooster
        learning_rate: 0.1

        verbose: 0
        class_weight: balanced
        max_iter: 1000
        l2_regularization: 0.3
        early_stopping: True
        max_leaf_nodes: 100
      
hyperparameters:
  FeatureSelector:
    features:
      default: ${features.all_features}
  OptBinningTransformer:
    max_n_prebins:
      type: int
      max: 1000
      min: 2
      default: 100
    min_prebin_size:
      type: float
      max: 0.5
      min: 0.02
      default: 0.05
    column:
      default: ${features.cat_features}
  HistBooster:
    learning_rate:
      type: float
      max: 1
      min: 0.01
      default: 0.1
    max_iter:
      type: int
      max: 10000
      min: 100
      default: 1000
    l2_regularization:
      type: float
      max: 10
      min: 0.001
      default: 0.3
    early_stopping:
      default: True
    max_leaf_nodes:
      type: int
      max: 1000
      min: 10
      default: 100
    max_depth:
      type: int
      max: 1000
      min: 1
      default: 100
    max_bins:
      type: int
      max: 255
      min: 2
      default: 255
    class_weight:
      default: balanced
