# config.yaml
defaults:
  - features: features
  - _self_


data_pipeline:
 _target_: model_forge.data.datapipeline.PandasDataPipeline
 steps:
  - _target_: data_pipeline.pipelinesteps.get_age
    _partial_: true
    column: birth_259D_last
  - _target_: data_pipeline.pipelinesteps.change_missing
    _partial_: true
    columns: ['housetype_905L_last', 'education_927M_last', 'credacc_cards_status_52L_mode', 'familystate_447L_last', 'credacc_cards_status_52L_last', 'classificationofcontr_400M_mode', 'credtype_322L_last', 'cardtype_51L_last', 'cardtype_51L_mode']

model:
  model_steps: 
    - FeatureFilter:
        _target_: model.feature_selector.FeatureFilter
        features: ${features.all_features}
    - OptBinningTransformer:
        _target_: model.binning.OptBinningTransformer
        variable_names: ${features.cat_features}
        max_n_prebins: 674
        min_prebin_size: 0.04386525609119459
        random_state: 42
    - SelectFromModel:
        _target_: model.feature_selector.FeatureSelector
        estimator: 
          _target_: model.booster.HistBooster
          class_weight: balanced
          max_iter: 3997
          l2_regularization: 2.525756277489002
          early_stopping: True
          max_leaf_nodes: 106
          max_bins: 196
          max_depth: 605
          random_state: 42
        threshold: 0.001

    - HistGradientBoostingClassifier:
        _target_: sklearn.ensemble.HistGradientBoostingClassifier
        learning_rate: 0.05723818391467435

        verbose: 0
        class_weight: balanced
        max_iter: 3997
        l2_regularization: 2.525756277489002
        early_stopping: True
        max_leaf_nodes: 106
        max_bins: 196
        max_depth: 605
        random_state: 42
      
hyperparameters:
  FeatureFilter:
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: features
      trial_type: default
      default_value: ${features.all_features}
    
  OptBinningTransformer:
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: max_n_prebins
      trial_type: int
      search_space: 
        - 2
        - 1000
      default_value: 100
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: min_prebin_size
      trial_type: float
      search_space: 
        - 0.02
        - 0.5
      default_value: 0.05
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: variable_names
      trial_type: default
      default_value: ${features.cat_features}
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: random_state
      trial_type: default
      default_value: 42

  SelectFromModel:
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: threshold
      trial_type: float
      search_space: 
        - 0.001
        - 0.01
      default_value: 0.005
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: estimator
      trial_type: default
      default_value: 
        _target_: model.booster.HistBooster


  HistGradientBoostingClassifier:
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: learning_rate
      trial_type: float
      search_space: 
        - 0.01
        - 1
      default_value: 0.1
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: max_iter
      trial_type: int
      search_space: 
        - 100
        - 10000
      default_value: 1000
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: l2_regularization
      trial_type: float
      search_space: 
        - 0.001
        - 10
      default_value: 0.3
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: early_stopping
      trial_type: default
      default_value: True
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: max_leaf_nodes
      trial_type: int
      search_space: 
        - 10
        - 1000
      default_value: 100
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: max_depth
      trial_type: int
      search_space: 
        - 1
        - 1000
      default_value: 100
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: max_bins
      trial_type: int
      search_space: 
        - 2
        - 255
      default_value: 255
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: class_weight
      trial_type: default
      default_value: balanced
    - _target_: model_forge.model.modelorchastrator.TuningParameter
      parameter_name: random_state
      trial_type: default
      default_value: 42
