data:
  person_1:
    time_col: []
    agg_columns:
      - name: childnum_185L
        base_feature_name: childnum_185L_mean
        aggregation: 
          _target_: data_pipeline.pipes.mean
          _partial_: true
      - name: housetype_905L
        base_feature_name: housetype_905L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: familystate_447L
        base_feature_name: familystate_447L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: education_927M
        base_feature_name: education_927M_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true

  static_0:
    time_col: []
    agg_columns:
      - name: cardtype_51L
        base_feature_name: cardtype_51L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: credtype_322L
        base_feature_name: credtype_322L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: numinstls_657L
        base_feature_name: numinstls_657L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: numinstlsallpaid_934L
        base_feature_name: numinstlsallpaid_934L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: numinstlswithdpd5_4187116L
        base_feature_name: numinstlswithdpd5_4187116L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: cardtype_51L
        base_feature_name: cardtype_51L_mode
        aggregation: 
          _target_: data_pipeline.pipes.mode
          _partial_: true
      - name: avginstallast24m_3658937A
        base_feature_name: avginstallast24m_3658937A_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: downpmt_116A
        base_feature_name: downpmt_116A_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      




  credit_bureau_a_1:
    time_col:
      - dateofrealrepmt_138D
    agg_columns:
      - name: numberofcontrsvalue_358L
        base_feature_name: numberofcontrsvalue_358L_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true
      - name: nominalrate_281L
        base_feature_name: nominalrate_281L_min
        aggregation: 
          _target_: data_pipeline.pipes.min
          _partial_: true
      - name: classificationofcontr_400M
        base_feature_name: classificationofcontr_400M_mode
        aggregation: 
          _target_: data_pipeline.pipes.mode
          _partial_: true
      - name: totaldebtoverduevalue_178A
        base_feature_name: totaldebtoverduevalue_178A_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true
      - name: overdueamount_31A
        base_feature_name: overdueamount_31A_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true
      - name: residualamount_488A
        base_feature_name: residualamount_488A_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true

  credit_bureau_a_2:
    time_col: []
    agg_columns:
      - name: collater_valueofguarantee_876L
        base_feature_name: collater_valueofguarantee_876L_mean
        aggregation: 
          _target_: data_pipeline.pipes.mean
          _partial_: true
      - name: pmts_overdue_1140A
        base_feature_name: pmts_overdue_1140A_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true
      - name: pmts_overdue_1140A
        base_feature_name: pmts_overdue_1140A_min
        aggregation: 
          _target_: data_pipeline.pipes.min
          _partial_: true
      - name: pmts_overdue_1140A
        base_feature_name: pmts_overdue_1140A_mean
        aggregation: 
          _target_: data_pipeline.pipes.mean
          _partial_: true

  applprev_2:
    time_col: []
    agg_columns:
      - name: credacc_cards_status_52L
        base_feature_name: credacc_cards_status_52L_mode
        aggregation: 
          _target_: data_pipeline.pipes.mode
          _partial_: true
      - name: credacc_cards_status_52L
        base_feature_name: credacc_cards_status_52L_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true


  applprev_1:
    time_col: []
    agg_columns:
      - name: mainoccupationinc_437A
        base_feature_name: mainoccupationinc_437A_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true

  debitcard_1:
    time_col:
      - openingdate_857D
    agg_columns:
      - name: last180dayaveragebalance_704A
        base_feature_name: last180dayaveragebalance_704A_last
        aggregation: 
          _target_: data_pipeline.pipes.last
          _partial_: true
      - name: last180dayaveragebalance_704A
        base_feature_name: last180dayaveragebalance_704A_mean
        aggregation: 
          _target_: data_pipeline.pipes.mean
          _partial_: true
      - name: last180dayaveragebalance_704A
        base_feature_name: last180dayaveragebalance_704A_max
        aggregation: 
          _target_: data_pipeline.pipes.max
          _partial_: true
