name: Update Mkdocs
on:
    push:
      branches:
        - main
permissions:
    contents: write

jobs:


    poetry-install:
        uses: BartvanWoesik/workflow-forge/.github/workflows/mkdocs-deploy.yml@main
    
