name: Test for Poetry


on:
    workflow_dispatch:

jobs:

    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

    poetry-install:
        uses: BartvanWoesik/workflow-forge/.github/workflows/setup-poetry.yml@main
    
