name: Test for Poetry
permissions:
    contents: write

on:
    workflow_dispatch:

jobs:


    poetry-install:
        uses: BartvanWoesik/workflow-forge/.github/workflows/setup-poetry.yml@main
    
